#!/bin/bash
echo "🌟 CLOUDFLARE SETUP (MUCH EASIER):"
echo ""
echo "1. Go to cloudflare.com (FREE)"
echo "2. Add all 3 domains"
echo "3. Cloudflare gives you 2 nameservers"
echo "4. Update ONLY nameservers in GoDaddy (once per domain)"
echo "5. Cloudflare automatically manages all DNS"
echo ""
echo "✅ RESULT: One nameserver change = automatic everything"
echo ""
echo "Your target IP: 35.201.89.202"
echo "Cloudflare will automatically:"
echo "- Handle SSL certificates"
echo "- Manage DNS records"  
echo "- Provide CDN acceleration"
echo "- Give you a simple dashboard"
